### ISSUE TITLE
Warning: Error in TimeProfile plot 31.  The formula 1 for unit µmol/l evaluates to a non-finite value (NaN, Inf, -Inf)

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/QualificationRunner#68] opened 2020-05-25 19:04 UTC
I receive this error when running a qualification plan. Any idea what this is supposed to mean? The plot is supposed to be created from the "AllPlots"-Section of the qualificiation plan, so just re-creating a plot from PK-Sim. I have no idea where to look.

**Comment by Yuri05** [comment] 2020-05-25 21:53
This error message comes from the Reporting Engine, not from the QualificationRunner.
https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox-Core/blob/099d1c9528f82e5aa77c0fa73821033d672d904b/code/auxiliaries/getUnitFactor.m#L75

Seems to be an issue with the units conversion (missing mol weight in an observed data set?). You could set the breakpoint in the Matlab Code to figure out what happens.

Which version of RE are ayou using? Can you try the latest one (not released yet)? 
https://ci.appveyor.com/project/open-systems-pharmacology-ci/reporting-engine/build/artifacts

**Comment by PavelBal** [comment] 2020-05-26 08:40
Yes, it is the missing MW, thank you @Yuri05 . But how can I add the missing MW to the data??

The "molecule" thas has been selected during import is not present in the project, and I cannot change the molecule in the "Observed Data" view in PK-Sim:

![image](https://user-images.githubusercontent.com/25903040/82879468-4785e480-9f3d-11ea-8e07-4c694cfc296b.png)

**Comment by PavelBal** [comment] 2020-05-26 08:41
Wait, I just see - there is the field "Molecular weight" which is filled out.

**Comment by PavelBal** [comment] 2020-05-26 08:59
Ok, obviously the Reporting Engine does not care about the MW stored in Observed Data, it always tries to find the respective compound in the simulation (in a very shady way):

https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/c4031220e9ae589ffa4757461cd8fd9010052a77/src/code/qualification/getMolecularWeightForPath.m#L35

Any advice what to do except for re-importing the data?

**Comment by Yuri05** [comment] 2020-05-26 13:10
>obviously the Reporting Engine does not care about the MW stored in Observed Data, it always tries to find the respective compound in the simulation

So your observed data was created for a compound X which is not in the simulation? Or is it unrelated to any compound?

**Comment by msevestre** [comment] 2020-05-26 13:15
@PavelBal The meta data are not exported to the reporting engine. Only the CSV Values

>Any advice what to do except for re-importing the data?

Do not expect meta data to be used

**Comment by Yuri05** [comment] 2020-05-26 14:56
Well, as a workaround you could create compound with the name X and your target mol weight into a simulation (without any administration).
Alternatively: wait for the reimplementation in R ;)

**Comment by msevestre** [comment] 2020-05-26 14:58
@Yuri05 EVen reimplementation in R will not use meta data as long as we only export csv

**Comment by PavelBal** [comment] 2020-05-26 18:52
> Well, as a workaround you could create compound with the name X and your target mol weight and add it into your simulations (without any administration).

Yepp, did exactly this...

> EVen reimplementation in R will not use meta data as long as we only export csv
But the snapshots have these data, so why not use it?

**Comment by msevestre** [comment] 2020-05-26 18:58
As long as we only export csv :) The proof is in the pudding

**Comment by Yuri05** [comment] 2024-12-27 15:45
Assume the issue is fixed in the R-RE. Closing

**Closed by Yuri05** 2024-12-27 15:45 UTC
